server:
  name: servername
  ipaddress: 10.0.0.0
  common-key: commonserver
---
spring:
  config:
    activate:
      on-profile: development
server:
  name: DevelopmentServer
  ipaddress: 127.0.0.0

---
spring:
  config:
    activate:
      on-profile: production
server:
  name: ProductionServer
  ipaddress: 17.10.02.03
---